[tool.poetry]
name = "political_party_analysis"
version = "0.1.0"
description = ""
authors = ["Iswariya Manivannan <iswariya.m17@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<=3.12"
requests = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
scikit-learn = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
black = "*"
flake8 = "*"
mypy = "*"
pytest-mock = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
